### ISSUE TITLE
web-capture初始化报错

### ISSUE THREAD

**Issue by CBulFel** [jordiwang/web-capture#1]
```
   import 'web-capture/web-capture'
  const webCapture = new WebCapture({
				onInit() {
					console.error('===== wasm 初始化完成 =====')
					debugger
					webCapture.capture(this.uploadItem.file, 5 * 1000, (imgDataUrl, imgInfo) => {
						const deltaTime = Date.now() - startTime
						debugger
						console.log(`耗时：${deltaTime}ms<br>宽度：${imgInfo.width}<br>高度：${imgInfo.height}<br>时长：${imgInfo.duration / 1000000}s`)
					})
				},
  })

```

**error:**

Uncaught SyntaxError: Unexpected token '<'

**Comment by jordiwang** [comment]
import src/index.js 试试呢

**Comment by jordiwang** [comment]
> ```
>    import 'web-capture/web-capture'
>   const webCapture = new WebCapture({
> 				onInit() {
> 					console.error('===== wasm 初始化完成 =====')
> 					debugger
> 					webCapture.capture(this.uploadItem.file, 5 * 1000, (imgDataUrl, imgInfo) => {
> 						const deltaTime = Date.now() - startTime
> 						debugger
> 						console.log(`耗时：${deltaTime}ms<br>宽度：${imgInfo.width}<br>高度：${imgInfo.height}<br>时长：${imgInfo.duration / 1000000}s`)
> 					})
> 				},
>   })
> ```
> 
> **error:**
> 
> Uncaught SyntaxError: Unexpected token '<'

imporr src/index.js 试试呢

**Comment by jordiwang** [comment]
另外可以试下直接用外链的方式引用
