### ISSUE TITLE
ts格式不能截图

### ISSUE THREAD

**Issue by cllee1214** [jordiwang/web-capture#10]
如题，ts格式的不能截图。是编码不支持吗  还是什么原因？
谢谢

**Comment by cllee1214** [comment]
@cllee1214 编译选项增加ts容器。

**Comment by RolkerMan** [comment]
> @cllee1214 编译选项增加ts容器。

请问知道怎么支持 wmv 格式吗，需要怎样增加编译选项，我这样尝试过，不行：
script/build_ffmpeg-emcc.sh
在以上文件添加编译选项（截图的右边）：

![Snipaste_2023-08-25_16-02-34](https://github.com/jordiwang/web-capture/assets/14216401/e3b598ec-238e-4f8c-b890-7fdc425e1765)

对应 wmv 视频用 FFmpeg 查看信息是这样的：

Input #0, asf, from 'wmv_1280_4_9MB.wmv':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42mp41isomavc1
    encoder         : Lavf57.19.100
  Duration: 00:00:30.59, start: 0.000000, bitrate: 1274 kb/s
  Stream #0:0: Video: wmv2 (WMV2 / 0x32564D57), yuv420p, 1280x720, SAR 1:1 DAR 16:9, 30 fps, 30 tbr, 1k tbn
  Stream #0:1: Audio: wmav2 (a[1][0][0] / 0x0161), 48000 Hz, 2 channels, fltp, 128 kb/s
