### ISSUE TITLE
图片旋转了

### ISSUE THREAD

**Issue by gx12358** [jordiwang/web-capture#14]
部分手机拍摄的视频，截取出来后，图片旋转了

**Comment by jordiwang** [comment]
是视频源就是旋转的，截取的时候不会对图像做额外的处理。一般是 iOS手机会有这个问题，可以在代码中兼容下

**Comment by jordiwang** [comment]
> 部分手机拍摄的视频，截取出来后，图片旋转了

是视频源就是旋转的，截取的时候不会对图像做额外的处理。一般是 iOS手机会有这个问题，可以在代码中兼容下
