### ISSUE TITLE
请问下该ffmpeg构建版本能做视频裁剪吗。

### ISSUE THREAD

**Issue by dlmys** [jordiwang/web-capture#3]
网上大部分实现了视频裁剪的ffmpeg wasm版本都在10MB左右，想请问下该版本可以实现视频的裁剪吗。

**Comment by jordiwang** [comment]
> 网上大部分实现了视频裁剪的ffmpeg wasm版本都在10MB左右，想请问下该版本可以实现视频的裁剪吗。

可以的，目前测试的常见的视频格式都可以支持
